packman/bookings/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

import views

urlpatterns = [
  # Property Management
  # url(r'^$', views.booking_index, name='package.index'),  
  url(r'^$', views.booking_list, name='booking.list'),
  url(r'^auth/$', views.booking_auth, name='booking.auth'),
  url(r'^payment/success/$', views.booking_payment_success, name='booking.payment.success'),
  url(r'^payment/error/$', views.booking_payment_error, name='booking.payment.error'),
  url(r'^payment/cancel/$', views.booking_payment_cancel, name='booking.payment.cancel'),
  url(r'^invoice/(?P<payment_hash>[0-9a-zA-Z]+)/$', views.booking_payment, name='booking.payment'),
  url(r'^(?P<booking_id>[a-zA-Z0-9]+)/$', views.booking_info, name='booking.info'),
  url(r'^(?P<booking_id>[a-zA-Z0-9]+)/review/$', views.booking_review, name='booking.review'),
  url(r'^(?P<booking_id>[a-zA-Z0-9]+)/review/(?P<order_id>[0-9]+)/(?P<order_item_id>[0-9]+)/remove_item$', views.booking_order_item_remove, name='booking.order.item.remove'),
  url(r'^(?P<booking_id>[a-zA-Z0-9]+)/review/(?P<order_id>[0-9]+)/(?P<promo_id>[0-9]+)/remove_promocode$', views.booking_promo_code_remove, name='booking.order.promo_code.remove'),
]

packman/packman/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 	url(r'^', include('public.urls')),
    url(r'^renzo/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^packages/', include('packages.urls')),
    url(r'^booking/', include('bookings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

packman/bookinglist/models.py
from __future__ import unicode_literals

from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class BookingList(models.Model):
  CHOICES = [(i,i) for i in range(0,10)]
  VOID = -1
  NONE = 0
  CONFIRMED = 1
  BLOCKED =2
  BOOKING_STATUS = (
    (VOID, 'Void'),
    (NONE, 'Not Confirmed'),
    (CONFIRMED, 'Confirm'),
    (BLOCKED, 'Blocked'),
  )
  booking_id = models.CharField(max_length = 20, null = False, blank = False)
  checkin = models.DateField(null=False)
  checkout = models.DateField(null=False)
  property = models.CharField(max_length = 300, null = True, blank = True)
  guest_name = models.CharField(max_length = 100, null = True, blank = True)
  guest_phone = PhoneNumberField(null=True, blank=True)
  booking_status = models.IntegerField(default=NONE, choices=BOOKING_STATUS, null=False)
  no_of_guest = models.IntegerField(default=1, null=False, choices=CHOICES)
  no_of_nights = models.IntegerField(default=1, null=False)
  rate = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
  total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
  # Status
  created = models.DateTimeField(auto_now_add=True,  editable=False)
  time = models.DateTimeField(auto_now=True,  editable=False)
  status = models.BooleanField(default=1, null=False)

packman/bookings/models.py
from __future__ import unicode_literals
import os, datetime
from binascii import hexlify
from decimal import Decimal
from django.db import models
from general.models import PackageLength, Guest, Promo, Addon
from packages.models import Package

# Create your models here.

def increment_booking_number():
  last_booking = Booking.objects.all().order_by('id').last()
  if not last_booking:
    return 'RNH' + str(datetime.date.today().year) + str(datetime.date.today().month).zfill(2) + '0000'
  booking_id = last_booking.booking_id
  booking_int = int(booking_id[9:13])
  new_booking_int = booking_int + 1
  new_booking_id = 'RNH' + str(str(datetime.date.today().year)) + str(datetime.date.today().month).zfill(2) + str(new_booking_int).zfill(4)
  return new_booking_id

class Booking(models.Model):
  CHOICES = [(i,i) for i in range(0,10)]
  VOID = -1
  NONE = 0
  CONFIRMED = 1
  BLOCKED =2
  BOOKING_STATUS = (
    (VOID, 'Void'),
    (NONE, 'Not Confirmed'),
    (CONFIRMED, 'Confirm'),
    (BLOCKED, 'Blocked'),
  )
  booking_id = models.CharField(max_length = 20, default = increment_booking_number, null = True, blank = True, editable=False)
  checkin = models.DateField(null=False)
  checkout = models.DateField(null=False)
  length = models.ForeignKey(PackageLength, on_delete=models.PROTECT)
  package = models.ForeignKey(Package, on_delete=models.PROTECT)
  quantity = models.IntegerField(default=1, null=False, choices=CHOICES)

  booking_status = models.IntegerField(default=NONE, choices=BOOKING_STATUS, null=False)
  no_of_guest = models.IntegerField(default=1, null=False, choices=CHOICES)
  no_of_extra_bed = models.IntegerField(default=0, null=False, choices=CHOICES)
  guest = models.ForeignKey(Guest, on_delete=models.PROTECT)
  # Status
  created = models.DateTimeField(auto_now_add=True,  editable=False)
  time = models.DateTimeField(auto_now=True,  editable=False)
  status = models.BooleanField(default=1, null=False)

  def no_of_nights(self):
    delta =  self.checkout -  self.checkin
    no_of_night = int(delta.days)
    return no_of_night

  def __str__(self):
    return '%s' % (self.id)

class Order(models.Model):
  """ Order Model """
  ACTIVE = 1
  NULL = 0
  ORDER_STATUS = (
    (1, 'Active'),
    (0, 'Null')
  )
  CASH = 0
  BANK_TRANSFER = 1
  ONLINE_PAYMENT =2
  PAYMENT_METHOD = (
    (CASH, 'Cash'),
    (BANK_TRANSFER, 'Bank Transfer'),
    (ONLINE_PAYMENT, 'Online Payment'),
  )

  OPTIONS = (
    (0, 'Full Payment'),
    (1, 'Part Payment'),
  )
  # All booking, will be added to Invoice including parent
  booking = models.ForeignKey(Booking, on_delete=models.PROTECT,editable=False)

  promo = models.ForeignKey(Promo, on_delete=models.PROTECT, null=True)

  lock = models.BooleanField(default=False, null=False)
  order_status = models.IntegerField(default=1, choices=ORDER_STATUS, null=False)
  payment_method = models.IntegerField(default=0, choices=PAYMENT_METHOD, null=False)
  payment_type = models.IntegerField(choices=OPTIONS, default=0, null=False)

  # Records
  created = models.DateTimeField(auto_now_add=True) 
  time = models.DateTimeField(auto_now=True)
  status = models.IntegerField(default=1, null=False)

  class Meta:
    ordering = ('-created','-id')
  def __str__(self):
    return '%s' % (self.id)

  def payment_total(self):
    total = Decimal('0.00')
    for payment in self.payments.all().filter(payment_status=Payments.PAID):
      total = total + payment.total
    return round(total,2)

  def payment_left(self):
    return round(self.total() - self.payment_total(),2)

  def sub_total(self):
    total = Decimal('0.00')
    for item in self.items.all().exclude(status=0):
      total = total + item.total()
    return round(total,2)

  def charge(self):
    charge = self.sub_total() * 0.08
    return round(charge,2)

  def tax(self):
    tax = self.charge() * 0.15
    return round(tax,2)

  # Add Tax and service  
  def total(self):
    if self.promo: 
      return (self.sub_total() + self.charge() + self.tax() - round(self.promo.price,2)) 
    else : 
      return (self.sub_total() + self.charge() + self.tax()) 
    
class OrderItems(models.Model):
  order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name='items', null=True)
  description = models.CharField(max_length=500, null=True)

  booking = models.ForeignKey(Booking, on_delete=models.PROTECT, null=True)
  add_on = models.ForeignKey(Addon, on_delete=models.PROTECT, null=True)
  lock = models.BooleanField(default=True, null=False)

  # Price 
  price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
  quantity = models.IntegerField(default=1, null=False)
  tax = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
  discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

  # Records
  created = models.DateTimeField(auto_now_add=True) 
  time = models.DateTimeField(auto_now=True)
  status = models.IntegerField(default=1, null=False)

  def __str__(self):
    return '%s' % (self.id)

  def total(self):
    total = Decimal( str( (self.price * self.quantity) - self.discount ))
    return total.quantize(Decimal('0.01'))

def _createId():
  return hexlify(os.urandom(16))
  

def increment_invoice_number():
  last_invoice = Payments.objects.all().order_by('id').last()
  if not last_invoice:
    return 'INV' + str(datetime.date.today().year) + str(datetime.date.today().month).zfill(2) + '0000'
  invoice_no = last_invoice.invoice_no
  invoice_int = int(invoice_no[9:13])
  new_invoice_int = invoice_int + 1
  new_invoice_no = 'INV' + str(str(datetime.date.today().year)) + str(datetime.date.today().month).zfill(2) + str(new_invoice_int).zfill(4)
  return new_invoice_no

class Payments(models.Model):
  CASH = 0
  BANK_TRANSFER = 1
  ONLINE_PAYMENT =2
  PAYMENT_METHOD = (
    (CASH, 'Cash'),
    (BANK_TRANSFER, 'Bank Transfer'),
    (ONLINE_PAYMENT, 'Online Payment'),
  )

  NOTPAID = 0
  PAID = 1
  FAILED = -1
  PAYMENT_STATUS = (
    (NOTPAID, 'Not Paid'),
    (PAID, 'Paid'),
    (FAILED, 'Failed'),
  )
  invoice_no = models.CharField(max_length = 20, default = increment_invoice_number, null = True, blank = True, editable=False)
  hash = models.CharField(max_length=32, default=_createId, editable=False)
  void = models.BooleanField(default=False, null=False)
  booking = models.ForeignKey(Booking, on_delete=models.PROTECT)
  order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name='payments')
  total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
  payment_method = models.IntegerField(default=2, choices=PAYMENT_METHOD, null=False)
  payment_status = models.IntegerField(default=0, choices=PAYMENT_STATUS, null=False)

  due = models.DateField(null=True, blank=True)

  # Gateway Record
  # Payment gateway type used in transaction
  payment_gateway_type = models.CharField(max_length=20, null=True, blank=True)  # Map to PG_TYPE

  # Map to addedon
  transaction_date_time = models.DateTimeField(null=True, blank=True)

  # mode  (credit card/ CD - Cheque / Net Banking)
  mode = models.CharField(max_length=10, null=True, blank=True)   
  gateway_status = models.CharField(max_length=15, null=True, blank=True)
  amount = models.DecimalField(max_digits=19, decimal_places=2, default=0.00)

  # Unique id from PayU.in
  mihpayid = models.CharField(max_length=100, null=True, blank=True)
  bankcode = models.CharField(max_length=10, null=True, blank=True)

  # Reference number for the payment gateway (received in PG_TYPE)
  bank_ref_num = models.CharField(max_length=100, null=True, blank=True)   
  discount = models.DecimalField(max_digits=19, decimal_places=6, default=0)   
  additional_charges = models.DecimalField(max_digits=19, decimal_places=6, default=0) # Charged by Payu

  # Status of transaction in PayU system
  # Map to unmappedstatus(initiated/ in progress /dropped / bounced / captured / auth/ failed / usercancelled/ pending)
  txn_status_on_payu = models.CharField(max_length=20, null=True, blank=True)  
  hash_status = models.CharField(max_length=100, null=True, blank=True)

  # Records
  created = models.DateTimeField(auto_now_add=True) 
  time = models.DateTimeField(auto_now=True)
  status = models.IntegerField(default=1, null=False)

packman/payments/models.py
from __future__ import unicode_literals

import os
from binascii import hexlify
from django.db import models
from bookings.models import Order, Booking

def _createId():
  return hexlify(os.urandom(16))

# Create your models here.
class Payments(models.Model):
  CASH = 0
  BANK_TRANSFER = 1
  ONLINE_PAYMENT =2
  PAYMENT_METHOD = (
    (CASH, 'Cash'),
    (BANK_TRANSFER, 'Bank Transfer'),
    (ONLINE_PAYMENT, 'Online Payment'),
  )

  NOTPAID = 0
  PAID = 1
  FAILED = -1
  PAYMENT_STATUS = (
    (NOTPAID, 'Not Paid'),
    (PAID, 'Paid'),
    (FAILED, 'Failed'),
  )

  hash = models.CharField(max_length=32, default=_createId, editable=False)
  booking = models.ForeignKey(Booking, on_delete=models.PROTECT)
  order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name='payments')
  total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
  payment_method = models.IntegerField(default=2, choices=PAYMENT_METHOD, null=False)
  payment_status = models.IntegerField(default=0, choices=PAYMENT_STATUS, null=False)

  due = models.DateField(null=True)

  # Records
  created = models.DateTimeField(auto_now_add=True) 
  time = models.DateTimeField(auto_now=True)
  status = models.IntegerField(default=1, null=False)

packman/bookings/forms.py
import datetime
from django import forms
from .models import Booking, Order, OrderItems

class booking_email_form(forms.Form):
  email = forms.EmailField(required=True, label="Email", max_length="100", widget=forms.TextInput(attrs={'class':'input-group-field'}))
  email_form = forms.IntegerField(widget = forms.HiddenInput(), required=False, initial=1)

class booking_add_form(forms.ModelForm):
  campagin_start = datetime.datetime.strptime('12-25-2017', "%m-%d-%Y").date()
  campagin_end = datetime.datetime.strptime('01-01-2018', "%m-%d-%Y").date()

  if datetime.date.today() > campagin_start  :
    start_date = datetime.date.today()
  else :
    start_date = campagin_start

  delta =  campagin_end -  campagin_start
  campagin_days = int(delta.days)

  DATECHOICE=[(campagin_start + datetime.timedelta(hours=date*24), start_date + datetime.timedelta(hours=date*24)) for date in range(0,campagin_days)]
  checkin = forms.ChoiceField(choices=DATECHOICE)


  def __init__(self, *args, **kwargs):
    package = kwargs.pop('package', None)
    super(booking_add_form, self).__init__(*args, **kwargs)
    if package is not None:
      self.fields['length']  =  forms.ModelChoiceField(label="Package",queryset=package.length.all(), widget=forms.RadioSelect(),empty_label=None)
      self.fields['no_of_guest'] = forms.ChoiceField(choices= [(i,i) for i in range(1,package.base_occupancy+1)])
      self.fields['no_of_extra_bed'] = forms.ChoiceField(label="Extra *", choices=[(0, 'None')] + [(i,i) for i in range(1,package.number_of_extra_bed+1)], required=False)

  class Meta:
    model = Booking
    fields = ('checkin','length', 'no_of_guest', 'no_of_extra_bed')

class order_item_add_form(forms.ModelForm):
  CHOICES = [(i,i) for i in range(1, 10)]
  quantity = forms.ChoiceField(choices=CHOICES)
  addon_form = forms.IntegerField(widget = forms.HiddenInput(), required=False, initial=1)

  def __init__(self, *args, **kwargs):
    super(order_item_add_form, self).__init__(*args, **kwargs)
    self.fields['add_on'].label = "Avalible Add-on"
    self.fields['add_on'].empty_label = None
    
  class Meta:
    model = OrderItems
    fields =('add_on','quantity')
    widgets = {
        'add_on': forms.RadioSelect(),
    }

class order_promo_add_form(forms.Form):
  promo_code = forms.CharField(required=True, label="Promo Code", max_length="20", widget=forms.TextInput(attrs={'class':'input-group-field'}))
  promo_form = forms.IntegerField(widget = forms.HiddenInput(), required=False, initial=1)

class order_confirm_form(forms.Form):
  OPTIONS = (
    (0, 'Full Payment'),
    (1, 'Part Payment'),
  )
  #payment_type = forms.ChoiceField(choices=OPTIONS, widget=forms.RadioSelect(), required=True)
  payment_type = forms.IntegerField(widget = forms.HiddenInput(), required=False, initial=0)
  order_form = forms.IntegerField(widget = forms.HiddenInput(), required=False, initial=1)

packman/bookinglist/views.py
from django.shortcuts import render
from .models import BookingList
# Create your views here.


@login_required
def booking_list(request):
  data = {}

  bookings = BookingList.objects.order_by('-created')

  to_show = 10
  paginator = Paginator(bookings, to_show) # Show 25 contacts per page
  count = bookings.count
  page = request.GET.get('page')
  try:
      bookings = paginator.page(page)
  except PageNotAnInteger:
  # If page is not an integer, deliver first page.
      bookings = paginator.page(1)
  except EmptyPage:
  # If page is out of range (e.g. 9999), deliver last page of results.
      bookings = paginator.page(paginator.num_pages)

  data['count'] = count
  data['bookings'] = bookings
  data['title'] = "Bookings"
  return render(request, 'bookinglist/bookinglist.html', data)

packman/payments/views.py
from django.shortcuts import render

# Create your views here.

packman/bookings/templates/booking/booking_info.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="bg-white border bb">
  <div class="row padd-4-top">
    <div class="small-12 medium-8 columns">
      <h3>Review Booking</h3>
      <p class="cl-gray">it only takes 2 minutes to book!</p>
    </div>
    {% if booking.booking_status == 0 %}
      <div class="small-12 medium-4 columns text-right">
        <a href="#payments" class="button success push-4-top"> Pay Now </a>
      </div>
    {% endif %}
  </div>

  <div class="row padd-4-bottom">
    <div class="small-12 medium-8 large-9 columns push-4-top">
      <div class="row">
        <div class="small-12 medium-8 large-5 column push-4-bottom">
          <img {%if booking.package.image_1 %} src="{{ MEDIA_URL }}{{booking.package.image_1.url}}" {% else %} src="{% static 'images/default.png' %}" {%endif%}>  
        </div>
        <div class="small-12 medium-4 large-7 column">
          <h4>{{booking.package.name}}</h4>
          <ul class="no-bullet">
            <li><span class="cl-gray">{{booking.package.property_type_select}}</span></li>
            <li>{{booking.package.address_2}}</li>
          </ul>
          <div class="row border bt padd-4-top padd-4-bottom">
            <div class="small-6 medium-12 large-6 columns border br">
              <ul class="no-bullet">
                <li>Check-in : <strong>{{booking.checkin}}</strong></li>
                <li>Check-Out : <strong>{{booking.checkout}}</strong></li>
                <li><span class="cl-gray">Total length of stay {{booking.no_of_nights}} Night(s)</span></li>
              </ul>
            </div>
            <div class="small-6 medium-12 large-6 columns ">
            <ul class="no-bullet">
              <li>Guest : {{booking.no_of_guest}}</li>
              <li>Additional Guest : {{booking.no_of_extra_bed}}</li>
            </ul>
            </div>
          </div>
          <div class="row">
            <div class="small-12 border bt columns">
              <ul class="no-bullet padd-4-top">
                <li>Primary Guest Email : {{booking.guest.email}}</li>
                <li>Primary Guest Phone : {{booking.guest.phone}}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="small-12 medium-4 large-3 columns push-4-top">
      <div class="border b-all padd-4">
        <h4>Total : INR {{order.total}}</h4>
        <hr/>
        <h6>Booking status</h6>
        <button class="button expanded
          {% if booking.booking_status == 0 %}
            alert
          {% elif booking.booking_status == 1 %}
            success
          {% elif booking.booking_status == 2 %}
            warning
          {% else %}
            alert
          {% endif %}
        ">{{booking.get_booking_status_display}}</button>

        {% if booking.booking_status == 0 %}
          <p class="cl-gray">Your booking will be confirmed only after payment.</p>
        {% endif %}

        {% if not booking.booking_status == 0 %}
        <h6>Re-send booking email</h6>
        <form method="post">
        {% csrf_token %}
        <div class="row">
          <div class="small-12 columns">
            {% if email_form.non_field_errors %}
              {% for err in email_form.non_field_errors %}
                <span class="cl-red">{{ err }}</span>
              {% endfor %}
            {% endif %}
            <div class="input-group">
              {{email_form.email}}
              <div class="input-group-button">
                <input type="submit" class="button success" value="Send">
              </div>
            </div> 
          </div>
          {{email_form.email_form}}
        </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="row push-4-top">
  <div class="small-12 medium-12 large-8 column">
    <div class="bg-white border b-all padd-4 push-4-top">
      <h5>Order</h5>
      <p class="cl-gray">Itenery for your booking.</p>
      <div class="table-scroll">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Description</th>
              <th width="150">Price (INR)</th>
              <th width="150">Quantity</th>
              <th width="150">Total (INR)</th>
            </tr>
          </thead>
          <tbody>
          {% for item in order_items %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>
                {{item.description}}
                {% if item.booking %}
                  <br/> Guest : {{booking.no_of_guest}} | Nights : {{booking.no_of_nights}}
                  <br/> Checkin Date  : {{booking.checkin}} | Checkout Date : {{booking.checkout}} 
                {% endif %}
                {% if item.lock == False %}
                  <br/><a href="{% url 'booking.order.item.remove' booking.id order.id item.id %}">Delete</a>
                {% endif %}
              </td>
              <td>{{item.price}}</td>
              <td>{{item.quantity}}</td>            
              <td>{{item.total}}</td>
            </tr>
          {% endfor %}
            <tr>
              <td colspan="5" class="text-right"></td>
            </tr>
            <tr>
              <td colspan="4" class="text-right">Sub Total</td>
              <td>{{order.sub_total}}</td>
            </tr>
            <tr>
              <td colspan="4" class="text-right">Internet Handeling Fee</td>
              <td>{{order.charge}}</td>
            </tr>
            <tr>
              <td colspan="4" class="text-right">Tax</td>
              <td>{{order.tax}}</td>
            </tr>
            {% if order.promo %}
            <tr>
              <td colspan="4" class="text-right">
                Offer ({{order.promo.promo_code}})<br/>
                {{order.promo.description}}
              </td>
              <td>- {{order.promo.price}}</td>
            </tr>
            {% endif %}
            <tr>
              <td colspan="4" class="text-right">Total</td>
              <td>{{order.total}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="small-12 medium-12 large-4 column">
    <div class="bg-white border b-all padd-4 push-4-top" id="payments">
      <h5>Payments</h5>
      <p class="cl-gray">Payment options for your booking</p>
      <ul class="no-bullet">
        <li>Payment Type : {{order.get_payment_type_display}}</li>
        {% if order.payment_type == 1 %}
        <li>Amount Paid : INR {{order.payment_total}}</li>
        <li>Amount Left : INR {{order.payment_left}}</li>
        {% endif %}
      </ul>
      
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Payment ID</th>
            <th width="100">Amount</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{payment.invoice_no}}
            {% if payment.due %}
                  <br/>Due :{{payment.due}}
                {% endif %}
            </td>
            <td>INR {{payment.total}}</td>
            <td>
              {% if payment.payment_status == 1 %}
                <a href="{% url 'booking.payment' payment.hash %}" target="_blank" class="button tiny success">Paid (view Details)</a>
              {% elif payment.payment_status == 0 %}
                <a href="{% url 'booking.payment' payment.hash %}" class="button tiny alert">Pay Now</a>
              {% endif %}
            </td>   
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

packman/bookings/templates/booking/booking_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="bg-white border bb">
  <div class="row padd-4-top">
  	<div class="small-12 columns">
  		<h3>Bookings list</h3>
      <p class="cl-gray">Booings for Email : {{guest.email}} and Phone :  {{guest.phone}}</p>
  	</div>
  </div>
</div>
<div class="row push-4-top">
  <div class="small-12 medium-6 small-centered column">
    <div class="bg-white border b-all padd-4 push-4-top" data-equalizer-watch="order">
      {% if bookings %}
        <div class="table-scroll">
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Booking ID</th>
                <th>Booking Information</th>
                <th>Booking Status</th>
              </tr>
            </thead>
            <tbody>
            {% for booking in bookings %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'booking.info' booking.booking_id %}" target="_blank">{{booking.booking_id}}</a></td>
                <td>{{booking.package.name}} <br/>
                {{booking.no_of_guest}} {% if booking.no_of_extra_bed %} + {{booking.no_of_extra_bed}} {% endif %} Adult(s)<br/>
                <strong>Checkin : {{booking.checkin}}</strong> | <strong>Checkout : {{booking.checkout}}</strong>
                </td>
                <td> 
                  <button class="label
                  {% if booking.booking_status == 0 %}
                    alert
                  {% elif booking.booking_status == 1 %}
                    success
                  {% elif booking.booking_status == 2 %}
                    warning
                  {% else %}
                    alert
                  {% endif %}
                ">{{booking.get_booking_status_display}}</button>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <div class="row">
          <div class="small-12 columns text-center">
            <h2>No Bookings</h2>
          </div>
        </div>
        <div class="row">
          <div class="small-12 medium-4 large-3 small-centered columns">
            <img src="{{MEDIA_URL}} {% static 'images/icons/mountain.png' %}">
          </div>
        </div>
        <div class="row">
          <div class="small-12 columns text-center">
            <p class="cl-gray">There is no booking made on your account.</p>
            <a href="{% url 'package.list' %}" class="button large success">Find a Place to stay</a>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

packman/bookings/templates/booking/payment_cancel.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="oneAction">
  <div class="oneActionInner">
    <div class="oneActionContainer">
      <div class="row">
        <div class="large-8 medium-10 small-12 small-centered columns">
          <div class="bg-white border padd-4 b-all">
            <div class="row">
              <div class="column small-12">
                <a href="{% url 'public.home'%}" class="logo float-center"><img src="{% static 'images/logo.png' %}"/></a>
              </div>
            </div>
            <div class="row push-4-top">
              <div class="small-12 medium-12 medium-centered columns">
				<h4 class="text-center">It's Odd isn't it.</h4>
				<p>The following Payment was canceled from the user side. If you wish to proceed with booking, <a href="{% url 'booking.auth' %}">click here</a>.</p>
				<p>Enter the <strong>E-mail address</strong> and <strong>Mobile number</strong> used during registration and resume the booking.</p>
				<p>Thank you for choosing Roomnhouse</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}